### ISSUE TITLE
Stakeholder Discussion

### ISSUE THREAD

**Issue by JMStudiosJoe** [codeforsanjose/disaster-response-sj#1]

**Comment by JMStudiosJoe** [comment]
- General playbook/guidelines

**Comment by jeffreyxiong** [comment]
Most cities / counties / schools and similar organizations have emergency management plans. Those are a decent starting point to look at how organizations generally respond to emergency situations, manage volunteers, and coordinate. Many of them are really dense.

Santa Clara County one is surprisingly brief: http://www.sanjoseca.gov/DocumentCenter/View/47601

We should figure out where within the operations chain this project could help bridge a gap, and figure out government stakeholders from there. 

Link to San Jose Emergency Management website: https://www.sanjoseca.gov/index.aspx?NID=751
