### ISSUE TITLE
[Windows] Can't install and run the app without errors on Windows

### ISSUE THREAD

**Issue by sunnymui** [codeforsanjose/disaster-response-sj#43]
Tried to run and install the app on Windows 8 and it runs into several errors when doing `npm i` to install all the dependencies. 

Some of the errors were resolved by updating my node/npm version. My npm was at 2.15.5 and node was v4.4.5 which is way behind current versions of npm 6.4 and node 10.15.1. 

Easiest way for Windows people to update is to just [download the latest install file from the node website](https://nodejs.org/en/download/) and reinstall their node/npm. It'll reinstall everything to the latest version.

Still getting some errors when installing dependencies, but it does seem to get further. Looks like the next error to resolve is that it can't find Python, so I think I have to reset my Python env variable. I do have Python installed, though I did have to install it myself on Windows. 

Another interesting error is a failure at the bcrypt install script with a message that it's probably not a problem with npm. Have to check it out more.

I'm attaching the complete debug log here.
[2019-02-22T04_37_22_878Z-debug.log](https://github.com/codeforsanjose/disaster-response-sj/files/2892552/2019-02-22T04_37_22_878Z-debug.log)

**Comment by sunnymui** [comment]
Hmm I reinstalled Python before doing anything, just in case and that actually fixed the Python error. 

New critical red text error now though where it couldn't load the Visual C++ component VCBuild.exe, though it has steps to fix by installed the .NET Framework 2.0 SDK and install Microsoft Visual Studio 2005. Need to check if I have it or not

**Comment by sunnymui** [comment]
Actually, according to [this](https://stackoverflow.com/questions/21658832/npm-install-error-msb3428-could-not-load-the-visual-c-component-vcbuild-ex), I just need to install the windows build tools so I'm trying that first. 

Have to run it in PowerShell as Admin, which is different from the regular command prompt. Running `npm install -g --production windows-build-tools`  to install.

**Comment by sunnymui** [comment]
Left the installer running for like 10-11 hours and it seems like it just froze. Hard to tell because there's no indication that it's progressing or loading or anything. From what I've read, that installer can fail and not show any error messages or notify you of anything. I shut it down anyway and restarted my computer, just in case I have some process messing something up. Haven't tried running `npm install -g --production windows-build-tools` again, so not sure if it would work now after a fresh reboot. I'm wondering if this npm package is different than the full Visual Studio build tools install [because the gif they have of the process on their npm page looks really fast.](https://www.npmjs.com/package/windows-build-tools)

The other way to install build tools is to manually [download the visual studio 2015 c++ build tools installer executable](https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe) and then run that. Note that it can add something like 20-50gb of files to **all** of your drives from what I've read. It was quoting me around 4 gb which I was kind of iffy about because I have my system files partition as a separate drive that doesn't have a lot of free space.

Instead I just tried an npm start again to see if anything had changed.

Same critical red highlighted error:
`MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe"...(instructions telling me to install the .net 2.0 sdk, install visual studio, or add the location of the system path if it is installed)`

Decided to ignore that for now and just see if there's other errors I can fix.

The other important seeming errors were warnings about needing a peer of react 15/16 for various components but none being installed. More importantly, it was saying stuff like `'react-scripts' is not recognized as an internal or external command`

I figured maybe I can just manually install that, so I did:
`npm install react-scripts --save`

Then I tried running the app again with `npm start`

Surprisingly, it compiled successfully and made the page available in localhost. So I can see the actual web app now! Some kind of progress at least.

Just to summarize what I've done so far:

1. Install latest versions of Node and NPM
2. Install latest version of Python
3. Ran `npm install -g --production windows-build-tools` and let it run for like 10 hours before deciding it probably wasn't going anywhere and ending the process.
4. Restarting computer
5. Tried `npm i` again in the disaster-response-sj repo, gettting the same error messages
5. Manually installed react-scripts in the disaster-response-sj repo by running `npm install react-scripts --save`
6. Ran `npm start` which successfully started a localhost with the webapp launched in my browser.

I'm not sure if everything is working right though, since I'm still missing some dependencies. I'll check with the project lead. Might be enough for front end work though.

**Comment by JMStudiosJoe** [comment]
wow did not think would be this difficult to get running. Frontend looks to be working but still need to run the backend command `nodemon --exec babel-node server.js`. Then the page will load with a list of posts.

**Comment by sunnymui** [comment]
Found this helpful looking guide. I'm still reading through it, but it looks useful for the future and fairly recently published:
[https://spin.atomicobject.com/2018/06/18/windows-node-js/](https://spin.atomicobject.com/2018/06/18/windows-node-js/)

**Comment by sunnymui** [comment]
So previously I was unable to get `npm install --global --production windows-build-tools` to work without it hanging + freezing. After reading through [this thread](https://github.com/felixrieseberg/windows-build-tools/issues/152#issuecomment-432945646), it seems like the most stable version is the 4.0.0 version (current 5.1) at least if you're having issues installing. Disk space usage ended up being around 1 gb.

So if the latest version won't install for you, try `npm install --global --production windows-build-tools@4.0.0` because that worked for me.

After doing that, I ran `npm install` again, and I got some different errors. This time, it looks like bcrypt didn't install. I manually installed that with `npm install bcrypt --save`.  

Running `npm install` again **completed without throwing any critical errors!** However, it was still giving me several warnings that a bunch of react packages didn't detect react as a installed peer dependency. I manually installed react with `npm install react --save` twice for some reason it wasn't showing up when I did `npm list react` the first time, but installing it again made it appear.

Finally, running `npm install` completes successfully with only a warning about the optional dependency for the fsevents module not being supported on Windows, thus not being installed. All in all, I'd say mission accomplished finally.

**Comment by sunnymui** [comment]
If you want the TLDR on how I got the app to install without errors on Windows 8, you'll want to do the following (run PowerShell as an admin when using the console for the commands):

1. Install latest version of Node.js and NPM
2. Install latest version of Python (maybe unnecessary because Python is installed as part of windows-build-tools)
3. Install Windows Build Tools: `npm install -g --production windows-build-tools@4.0.0` 
4. Install bcrypt manually: `npm install bcrypt --save`
5. Install react manually: `npm install react --save`
6. Install app dependencies: `npm i`

If you encounter issues, you may have to restart your computer or run commands a second time. I'd also verify packages are actually installed by using `npm list <package name to check>` to see if they show up.

**Comment by sunnymui** [comment]
Previous post gets installation to work, but additional steps are necessary to get the app to run. Remember to do this in PowerShell with admin privileges:

1. Install Nodemon globally: `npm install -g nodemon` 
2. Install Babel globally: `npm install -g @babel/core @babel/cli @babel/node`
3. Ask project lead for the secrets file, download it, and put it in the `/config` directory of the project
4. Start the back end server: `nodemon --exec babel-node server.js`
5. Start the front end React app (open another PowerShell window): `npm start`

A tab should open automatically in your browser with the url `http://localhost:3000/` with the UI showing and a table of disaster information. 

To quit running the app, hit Ctrl + C in your PowerShell window and it'll ask you if you want to terminate the batch job. Enter Y and hit enter, and it'll stop the running process. You can do that in both windows to stop the front and back end or you can just close the windows.

**Comment by sunnymui** [comment]
Should probably update the readme with this info.

**Comment by JMStudiosJoe** [comment]
Can you make a branch and update the readme then make a PR for it?

Cheers,

- Joseph

**Comment by JMStudiosJoe** [comment]
Windows users have been able to get running thank you Sunny!!
