### ISSUE TITLE
FEMA Checklist details

### ISSUE THREAD

**Issue by JMStudiosJoe** [codeforsanjose/disaster-response-sj#44]
Tab has been created now needs content

**Comment by sunnymui** [comment]
Here's the [FEMA damage assessment operations manual.](https://www.fema.gov/media-library-data/1459972926996-a31eb90a2741e86699ef34ce2069663a/PDAManualFinal6.pdf).

Seems we're not exactly sure what should go here so might need to do some more research or meet with some people.

**Comment by sunnymui** [comment]
Here's a [FEMA disaster survivor checklist](https://www.fema.gov/media-library-data/1505143234654-0094f4d1a798c1d5175d7e11a114e77a/disaster-survivors-checklist.pdf)

**Comment by JMStudiosJoe** [comment]
great job
